"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var index_1 = __importDefault(require("../index"));
test('Is Tuesday a Business Day', function () {
    var tuesday = index_1.default().startOf('week').add(2, 'days');
    expect(tuesday.isBusinessDay()).toBe(true);
});
test('Is Sunday not a Business Day', function () {
    var tuesday = index_1.default().startOf('week');
    expect(tuesday.isBusinessDay()).toBe(false);
});
test('Is Christmas Not A Business Day', function () {
    var christmas = index_1.default('12-25-2020', 'MM-DD-YYYY');
    expect(christmas.isBusinessDay()).toBe(false);
    christmas = index_1.default('12-25-2019', 'MM-DD-YYYY');
    expect(christmas.isBusinessDay()).toBe(false);
    christmas = index_1.default('12-25-2018', 'MM-DD-YYYY');
    expect(christmas.isBusinessDay()).toBe(false);
    christmas = index_1.default('12-25-2017', 'MM-DD-YYYY');
    expect(christmas.isBusinessDay()).toBe(false);
    christmas = index_1.default('12-25-2016', 'MM-DD-YYYY');
    expect(christmas.isBusinessDay()).toBe(false);
    christmas = index_1.default('12-25-2015', 'MM-DD-YYYY');
    expect(christmas.isBusinessDay()).toBe(false);
});
test('Is MlkJr Not A Business Day', function () {
    var mlkJr = index_1.default('01-18-2016', 'MM-DD-YYYY');
    expect(mlkJr.isBusinessDay()).toBe(false);
    mlkJr = index_1.default('01-16-2017', 'MM-DD-YYYY');
    expect(mlkJr.isBusinessDay()).toBe(false);
    mlkJr = index_1.default('01-15-2018', 'MM-DD-YYYY');
    expect(mlkJr.isBusinessDay()).toBe(false);
    mlkJr = index_1.default('01-21-2019', 'MM-DD-YYYY');
    expect(mlkJr.isBusinessDay()).toBe(false);
    mlkJr = index_1.default('01-20-2020', 'MM-DD-YYYY');
    expect(mlkJr.isBusinessDay()).toBe(false);
    mlkJr = index_1.default('01-18-2021', 'MM-DD-YYYY');
    expect(mlkJr.isBusinessDay()).toBe(false);
});
test('Is Memorial Day Not A Business Day', function () {
    var memorialDay = index_1.default('05-30-2016', 'MM-DD-YYYY');
    expect(memorialDay.isBusinessDay()).toBe(false);
    memorialDay = index_1.default('05-29-2017', 'MM-DD-YYYY');
    expect(memorialDay.isBusinessDay()).toBe(false);
    memorialDay = index_1.default('05-28-2018', 'MM-DD-YYYY');
    expect(memorialDay.isBusinessDay()).toBe(false);
    memorialDay = index_1.default('05-27-2019', 'MM-DD-YYYY');
    expect(memorialDay.isBusinessDay()).toBe(false);
    memorialDay = index_1.default('05-25-2020', 'MM-DD-YYYY');
    expect(memorialDay.isBusinessDay()).toBe(false);
    memorialDay = index_1.default('05-31-2021', 'MM-DD-YYYY');
    expect(memorialDay.isBusinessDay()).toBe(false);
});
test('Is Independence Day Not A Business Day', function () {
    var independenceDay = index_1.default('07-04-2016', 'MM-DD-YYYY');
    expect(independenceDay.isBusinessDay()).toBe(false);
    independenceDay = index_1.default('07-04-2017', 'MM-DD-YYYY');
    expect(independenceDay.isBusinessDay()).toBe(false);
    independenceDay = index_1.default('07-04-2018', 'MM-DD-YYYY');
    expect(independenceDay.isBusinessDay()).toBe(false);
    independenceDay = index_1.default('07-04-2019', 'MM-DD-YYYY');
    expect(independenceDay.isBusinessDay()).toBe(false);
    independenceDay = index_1.default('07-03-2020', 'MM-DD-YYYY');
    expect(independenceDay.isBusinessDay()).toBe(false);
    independenceDay = index_1.default('07-05-2021', 'MM-DD-YYYY');
    expect(independenceDay.isBusinessDay()).toBe(false);
});
test('Is Labor Day Not A Business Day', function () {
    var laborDay = index_1.default('09-05-2016', 'MM-DD-YYYY');
    expect(laborDay.isBusinessDay()).toBe(false);
    laborDay = index_1.default('09-04-2017', 'MM-DD-YYYY');
    expect(laborDay.isBusinessDay()).toBe(false);
    laborDay = index_1.default('09-03-2018', 'MM-DD-YYYY');
    expect(laborDay.isBusinessDay()).toBe(false);
    laborDay = index_1.default('09-02-2019', 'MM-DD-YYYY');
    expect(laborDay.isBusinessDay()).toBe(false);
    laborDay = index_1.default('09-07-2020', 'MM-DD-YYYY');
    expect(laborDay.isBusinessDay()).toBe(false);
    laborDay = index_1.default('09-06-2021', 'MM-DD-YYYY');
    expect(laborDay.isBusinessDay()).toBe(false);
});
test('Is Veterans Day Not A Business Day', function () {
    var veteransDay = index_1.default('11-11-2016', 'MM-DD-YYYY');
    expect(veteransDay.isBusinessDay()).toBe(false);
    veteransDay = index_1.default('11-10-2017', 'MM-DD-YYYY');
    expect(veteransDay.isBusinessDay()).toBe(false);
    veteransDay = index_1.default('11-12-2018', 'MM-DD-YYYY');
    expect(veteransDay.isBusinessDay()).toBe(false);
    veteransDay = index_1.default('11-11-2019', 'MM-DD-YYYY');
    expect(veteransDay.isBusinessDay()).toBe(false);
    veteransDay = index_1.default('11-11-2020', 'MM-DD-YYYY');
    expect(veteransDay.isBusinessDay()).toBe(false);
    veteransDay = index_1.default('11-11-2021', 'MM-DD-YYYY');
    expect(veteransDay.isBusinessDay()).toBe(false);
});
test('Is Thanksgiving Day Not A Business Day', function () {
    var thanksgivingDay = index_1.default('11-24-2016', 'MM-DD-YYYY');
    expect(thanksgivingDay.isBusinessDay()).toBe(false);
    thanksgivingDay = index_1.default('11-23-2017', 'MM-DD-YYYY');
    expect(thanksgivingDay.isBusinessDay()).toBe(false);
    thanksgivingDay = index_1.default('11-22-2018', 'MM-DD-YYYY');
    expect(thanksgivingDay.isBusinessDay()).toBe(false);
    thanksgivingDay = index_1.default('11-28-2019', 'MM-DD-YYYY');
    expect(thanksgivingDay.isBusinessDay()).toBe(false);
    thanksgivingDay = index_1.default('11-26-2020', 'MM-DD-YYYY');
    expect(thanksgivingDay.isBusinessDay()).toBe(false);
    thanksgivingDay = index_1.default('11-25-2021', 'MM-DD-YYYY');
    expect(thanksgivingDay.isBusinessDay()).toBe(false);
});
test('Is Day After Thanksgiving Day Not A Business Day', function () {
    var dayAfterThanksgivingDay = index_1.default('11-25-2016', 'MM-DD-YYYY');
    expect(dayAfterThanksgivingDay.isBusinessDay()).toBe(false);
    dayAfterThanksgivingDay = index_1.default('11-24-2017', 'MM-DD-YYYY');
    expect(dayAfterThanksgivingDay.isBusinessDay()).toBe(false);
    dayAfterThanksgivingDay = index_1.default('11-23-2018', 'MM-DD-YYYY');
    expect(dayAfterThanksgivingDay.isBusinessDay()).toBe(false);
    dayAfterThanksgivingDay = index_1.default('11-29-2019', 'MM-DD-YYYY');
    expect(dayAfterThanksgivingDay.isBusinessDay()).toBe(false);
    dayAfterThanksgivingDay = index_1.default('11-27-2020', 'MM-DD-YYYY');
    expect(dayAfterThanksgivingDay.isBusinessDay()).toBe(false);
    dayAfterThanksgivingDay = index_1.default('11-26-2021', 'MM-DD-YYYY');
    expect(dayAfterThanksgivingDay.isBusinessDay()).toBe(false);
});
test('Is New Years Day Not A Business Day', function () {
    var newYearsDay = index_1.default('01-01-2016', 'MM-DD-YYYY');
    expect(newYearsDay.isBusinessDay()).toBe(false);
    newYearsDay = index_1.default('01-02-2017', 'MM-DD-YYYY');
    expect(newYearsDay.isBusinessDay()).toBe(false);
    newYearsDay = index_1.default('01-01-2018', 'MM-DD-YYYY');
    expect(newYearsDay.isBusinessDay()).toBe(false);
    newYearsDay = index_1.default('01-01-2019', 'MM-DD-YYYY');
    expect(newYearsDay.isBusinessDay()).toBe(false);
    newYearsDay = index_1.default('01-01-2020', 'MM-DD-YYYY');
    expect(newYearsDay.isBusinessDay()).toBe(false);
    newYearsDay = index_1.default('01-01-2021', 'MM-DD-YYYY');
    expect(newYearsDay.isBusinessDay()).toBe(false);
    newYearsDay = index_1.default('12-31-2021', 'MM-DD-YYYY');
    expect(newYearsDay.isBusinessDay()).toBe(false);
    newYearsDay = index_1.default('01-01-2022', 'MM-DD-YYYY');
    expect(newYearsDay.isBusinessDay()).toBe(false);
});
test('Is Christmas A Holiday', function () {
    var christmas = index_1.default('12-25-2020', 'MM-DD-YYYY');
    expect(christmas.isHoliday()).toBe(true);
    christmas = index_1.default('12-25-2019', 'MM-DD-YYYY');
    expect(christmas.isHoliday()).toBe(true);
    christmas = index_1.default('12-25-2018', 'MM-DD-YYYY');
    expect(christmas.isHoliday()).toBe(true);
    christmas = index_1.default('12-25-2017', 'MM-DD-YYYY');
    expect(christmas.isHoliday()).toBe(true);
    christmas = index_1.default('12-25-2015', 'MM-DD-YYYY');
    expect(christmas.isHoliday()).toBe(true);
});
test('Is MlkJr A Holiday', function () {
    var mlkJr = index_1.default('01-18-2016', 'MM-DD-YYYY');
    expect(mlkJr.isHoliday()).toBe(true);
    mlkJr = index_1.default('01-16-2017', 'MM-DD-YYYY');
    expect(mlkJr.isHoliday()).toBe(true);
    mlkJr = index_1.default('01-15-2018', 'MM-DD-YYYY');
    expect(mlkJr.isHoliday()).toBe(true);
    mlkJr = index_1.default('01-21-2019', 'MM-DD-YYYY');
    expect(mlkJr.isHoliday()).toBe(true);
    mlkJr = index_1.default('01-20-2020', 'MM-DD-YYYY');
    expect(mlkJr.isHoliday()).toBe(true);
    mlkJr = index_1.default('01-18-2021', 'MM-DD-YYYY');
    expect(mlkJr.isHoliday()).toBe(true);
});
test('Is Memorial Day A Holiday', function () {
    var memorialDay = index_1.default('05-30-2016', 'MM-DD-YYYY');
    expect(memorialDay.isHoliday()).toBe(true);
    memorialDay = index_1.default('05-29-2017', 'MM-DD-YYYY');
    expect(memorialDay.isHoliday()).toBe(true);
    memorialDay = index_1.default('05-28-2018', 'MM-DD-YYYY');
    expect(memorialDay.isHoliday()).toBe(true);
    memorialDay = index_1.default('05-27-2019', 'MM-DD-YYYY');
    expect(memorialDay.isHoliday()).toBe(true);
    memorialDay = index_1.default('05-25-2020', 'MM-DD-YYYY');
    expect(memorialDay.isHoliday()).toBe(true);
    memorialDay = index_1.default('05-31-2021', 'MM-DD-YYYY');
    expect(memorialDay.isHoliday()).toBe(true);
});
test('Is Independence Day A Holiday', function () {
    var independenceDay = index_1.default('07-04-2016', 'MM-DD-YYYY');
    expect(independenceDay.isHoliday()).toBe(true);
    independenceDay = index_1.default('07-04-2017', 'MM-DD-YYYY');
    expect(independenceDay.isHoliday()).toBe(true);
    independenceDay = index_1.default('07-04-2018', 'MM-DD-YYYY');
    expect(independenceDay.isHoliday()).toBe(true);
    independenceDay = index_1.default('07-04-2019', 'MM-DD-YYYY');
    expect(independenceDay.isHoliday()).toBe(true);
    independenceDay = index_1.default('07-03-2020', 'MM-DD-YYYY');
    expect(independenceDay.isHoliday()).toBe(true);
});
test('Is Labor Day A Holiday', function () {
    var laborDay = index_1.default('09-05-2016', 'MM-DD-YYYY');
    expect(laborDay.isHoliday()).toBe(true);
    laborDay = index_1.default('09-04-2017', 'MM-DD-YYYY');
    expect(laborDay.isHoliday()).toBe(true);
    laborDay = index_1.default('09-03-2018', 'MM-DD-YYYY');
    expect(laborDay.isHoliday()).toBe(true);
    laborDay = index_1.default('09-02-2019', 'MM-DD-YYYY');
    expect(laborDay.isHoliday()).toBe(true);
    laborDay = index_1.default('09-07-2020', 'MM-DD-YYYY');
    expect(laborDay.isHoliday()).toBe(true);
    laborDay = index_1.default('09-06-2021', 'MM-DD-YYYY');
    expect(laborDay.isHoliday()).toBe(true);
});
test('Is Veterans Day A Holiday', function () {
    var veteransDay = index_1.default('11-11-2016', 'MM-DD-YYYY');
    expect(veteransDay.isHoliday()).toBe(true);
    veteransDay = index_1.default('11-10-2017', 'MM-DD-YYYY');
    expect(veteransDay.isHoliday()).toBe(true);
    veteransDay = index_1.default('11-12-2018', 'MM-DD-YYYY');
    expect(veteransDay.isHoliday()).toBe(true);
    veteransDay = index_1.default('11-11-2019', 'MM-DD-YYYY');
    expect(veteransDay.isHoliday()).toBe(true);
    veteransDay = index_1.default('11-11-2020', 'MM-DD-YYYY');
    expect(veteransDay.isHoliday()).toBe(true);
    veteransDay = index_1.default('11-11-2021', 'MM-DD-YYYY');
    expect(veteransDay.isHoliday()).toBe(true);
});
test('Is Thanksgiving Day A Holiday', function () {
    var thanksgivingDay = index_1.default('11-24-2016', 'MM-DD-YYYY');
    expect(thanksgivingDay.isHoliday()).toBe(true);
    thanksgivingDay = index_1.default('11-23-2017', 'MM-DD-YYYY');
    expect(thanksgivingDay.isHoliday()).toBe(true);
    thanksgivingDay = index_1.default('11-22-2018', 'MM-DD-YYYY');
    expect(thanksgivingDay.isHoliday()).toBe(true);
    thanksgivingDay = index_1.default('11-28-2019', 'MM-DD-YYYY');
    expect(thanksgivingDay.isHoliday()).toBe(true);
    thanksgivingDay = index_1.default('11-26-2020', 'MM-DD-YYYY');
    expect(thanksgivingDay.isHoliday()).toBe(true);
    thanksgivingDay = index_1.default('11-25-2021', 'MM-DD-YYYY');
    expect(thanksgivingDay.isHoliday()).toBe(true);
});
test('Is Day After Thanksgiving Day A Holiday', function () {
    var dayAfterThanksgivingDay = index_1.default('11-25-2016', 'MM-DD-YYYY');
    expect(dayAfterThanksgivingDay.isHoliday()).toBe(true);
    dayAfterThanksgivingDay = index_1.default('11-24-2017', 'MM-DD-YYYY');
    expect(dayAfterThanksgivingDay.isHoliday()).toBe(true);
    dayAfterThanksgivingDay = index_1.default('11-23-2018', 'MM-DD-YYYY');
    expect(dayAfterThanksgivingDay.isHoliday()).toBe(true);
    dayAfterThanksgivingDay = index_1.default('11-29-2019', 'MM-DD-YYYY');
    expect(dayAfterThanksgivingDay.isHoliday()).toBe(true);
    dayAfterThanksgivingDay = index_1.default('11-27-2020', 'MM-DD-YYYY');
    expect(dayAfterThanksgivingDay.isHoliday()).toBe(true);
    dayAfterThanksgivingDay = index_1.default('11-26-2021', 'MM-DD-YYYY');
    expect(dayAfterThanksgivingDay.isHoliday()).toBe(true);
});
test('Is New Years Day A Holiday', function () {
    var newYearsDay = index_1.default('01-01-2016', 'MM-DD-YYYY');
    expect(newYearsDay.isHoliday()).toBe(true);
    newYearsDay = index_1.default('01-02-2017', 'MM-DD-YYYY');
    expect(newYearsDay.isHoliday()).toBe(true);
    newYearsDay = index_1.default('01-01-2018', 'MM-DD-YYYY');
    expect(newYearsDay.isHoliday()).toBe(true);
    newYearsDay = index_1.default('01-01-2019', 'MM-DD-YYYY');
    expect(newYearsDay.isHoliday()).toBe(true);
    newYearsDay = index_1.default('01-01-2020', 'MM-DD-YYYY');
    expect(newYearsDay.isHoliday()).toBe(true);
    newYearsDay = index_1.default('01-01-2021', 'MM-DD-YYYY');
    expect(newYearsDay.isHoliday()).toBe(true);
    newYearsDay = index_1.default('12-31-2021', 'MM-DD-YYYY');
    expect(newYearsDay.isHoliday()).toBe(true);
    newYearsDay = index_1.default('01-02-2023', 'MM-DD-YYYY');
    expect(newYearsDay.isHoliday()).toBe(true);
});
